### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by YourMajestyTheEye** [yodaluca23/School_Anti-Block#1]
It is just saying this over and over and won't stop

Now attempting to kill processes...
ERROR: The process "smart-agent-js-win.exe" not found.
ERROR: The process "makeca.exe" not found.
ERROR: The process "lsproxy.exe" with PID 6816 could not be terminated.
Reason: Access is denied.
ERROR: The process "client32.exe" not found.
ERROR: The process "Client32.exe" not found.
ERROR: The process "Runplugin64.exe" not found.
ERROR: The process "runplugin.exe" not found.
ERROR: The process "LSSASvc.exe" with PID 4128 could not be terminated.
Reason: Access is denied.

**Comment by yodaluca23** [comment]
> It is just saying this over and over and won't stop
> 
> 
> 
> Now attempting to kill processes...
> 
> ERROR: The process "smart-agent-js-win.exe" not found.
> 
> ERROR: The process "makeca.exe" not found.
> 
> ERROR: The process "lsproxy.exe" with PID 6816 could not be terminated.
> 
> Reason: Access is denied.
> 
> ERROR: The process "client32.exe" not found.
> 
> ERROR: The process "Client32.exe" not found.
> 
> ERROR: The process "Runplugin64.exe" not found.
> 
> ERROR: The process "runplugin.exe" not found.
> 
> ERROR: The process "LSSASvc.exe" with PID 4128 could not be terminated.
> 
> Reason: Access is denied.


Yeah, sorry it looks like your school blocked your access to ending tasks... sadly, this software won't work for you...
